version: 0.2

env:
  parameter-store:
    VAULT_SECRET_ID: VAULT_SECRET_ID_CODEBUILD

phases:
  # install:
  #   commands:
  #     - echo ----------------------------
  #     - echo Entered the install phase...
  #     - echo ----------------------------
  #     - wget -O- https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo | sudo tee /etc/yum.repos.d/hashicorp.repo
  #     - sudo yum --quiet --assumeyes install vault
  pre_build:
    commands:
      - echo ------------------------------
      - echo Entered the pre_build phase...
      - echo ------------------------------
      - echo
      - echo ----------------------
      - echo Retrieving Vault token
      - echo ----------------------
      - VAULT_TOKEN=`curl -k -q -s --request POST \
                     --data '{"role_id":"'$VAULT_ROLE_ID'","secret_id":"'$VAULT_SECRET_ID'"}' \
                     $VAULT_ADDR/v1/auth/approle/login | jq -r '.auth | .client_token'`
      - echo ----------------------
      - echo
      - echo -----------------------
      - echo Retrieve KV using token
      - echo -----------------------
      - VAULT_DATA=`curl -k -q -s -H "X-Vault-Token:$VAULT_TOKEN" -X GET $VAULT_ADDR/v1/best-family/secrets/data/codebuild`
      - echo ---------------
      - echo Display KV info
      - echo ---------------
      - echo $VAULT_DATA
