version: 0.2

env:
  variables:
    VAULT_ADDR: "lorem ipsum"
    VAULT_TOKEN: "lorem ipsum"
    VAULT_NAMESPACE: "lorem ipsum"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - wget -O- https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo | sudo tee /etc/yum.repos.d/hashicorp.repo
      - sudo yum -y install vault
      - sudo vault version
  build:
    commands:
      - echo Entered the build phase...
      - echo Display VAULT_ variables
      - echo VAULT_ADDR $VAULT_ADDR
      - echo VAULT_TOKEN $VAULT_TOKEN
      - echo VAULT_NAMESPACE $VAULT_NAMESPACE
